/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "var(--color-surface-tint)",
        "background": "var(--color-background)",
        "outline-variant": "var(--color-outline-variant)",
        "on-secondary-fixed-variant": "#810081",
        "inverse-primary": "#006970",
        "primary": "var(--color-primary)",
        "on-error": "#690005",
        "tertiary-container": "#e1d2ff",
        "on-secondary-fixed": "#380038",
        "outline": "var(--color-outline)",
        "surface": "var(--color-surface)",
        "inverse-on-surface": "#2a3043",
        "on-secondary": "#5b005b",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#23005b",
        "primary-fixed-dim": "#00dbe9",
        "secondary-fixed": "#ffd7f5",
        "surface-container-high": "var(--color-surface-container-high)",
        "secondary-fixed-dim": "#ffabf3",
        "on-tertiary": "#3c0090",
        "surface-bright": "#33394c",
        "on-primary-container": "#006970",
        "surface-variant": "var(--color-surface-variant)",
        "inverse-surface": "#dce1fb",
        "on-primary-fixed-variant": "#004f54",
        "on-background": "var(--color-on-background)",
        "on-secondary-container": "#500050",
        "tertiary-fixed-dim": "#d1bcff",
        "error": "#ffb4ab",
        "tertiary-fixed": "#e9ddff",
        "surface-container": "#191f31",
        "on-tertiary-container": "#7213ff",
        "secondary": "#ffabf3",
        "on-primary-fixed": "#002022",
        "surface-dim": "var(--color-surface)",
        "on-primary": "var(--color-on-primary)",
        "surface-container-low": "#151b2d",
        "secondary-container": "#fe00fe",
        "on-surface": "var(--color-on-surface)",
        "primary-fixed": "#7df4ff",
        "on-tertiary-fixed-variant": "#5700c9",
        "error-container": "#93000a",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "tertiary": "#faf3ff",
        "surface-container-highest": "#2e3447",
        "primary-container": "#00f0ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "stack-lg": "32px",
        "margin": "48px",
        "stack-sm": "8px",
        "unit": "4px",
        "gutter": "24px",
        "stack-md": "16px",
        "container-max": "1440px",
        "glass-padding": "24px"
      },
      fontFamily: {
        "headline-md": ["Space Grotesk"],
        "data-mono": ["Space Grotesk"],
        "body-md": ["Inter"],
        "display-lg": ["Space Grotesk"],
        "body-lg": ["Inter"],
        "headline-xl": ["Space Grotesk"],
        "label-caps": ["Space Grotesk"]
      },
      fontSize: {
        "headline-md": ["32px", { "lineHeight": "1.3", "letterSpacing": "0em", "fontWeight": "500" }],
        "data-mono": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.6", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "display-lg": ["72px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.2em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
