// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 25/04/2026, 03:05:25
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Ali Raza/Desktop/AI_Simulator/risk-analyzer/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ali Raza/Desktop/AI_Simulator/risk-analyzer/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ali Raza/Desktop/AI_Simulator/risk-analyzer/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ali Raza/Desktop/AI_Simulator/risk-analyzer/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ali Raza/Desktop/AI_Simulator/risk-analyzer/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Ali Raza/Desktop/AI_Simulator/risk-analyzer/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Ali Raza/Desktop/AI_Simulator/risk-analyzer/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Ali Raza/Desktop/AI_Simulator/risk-analyzer/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ali Raza/Desktop/AI_Simulator/risk-analyzer/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ali Raza/Desktop/AI_Simulator/risk-analyzer/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ali Raza/Desktop/AI_Simulator/risk-analyzer/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;