<template>
  <div v-if="report" class="fade-in-up report-page">
    <!-- Top Actions -->
    <div class="report-actions">
      <NuxtLink to="/dashboard" class="back-btn">
        <span class="material-symbols-outlined">arrow_back</span>
        Back to Dashboard
      </NuxtLink>
      <button @click="printReport" class="export-btn">
        <span class="material-symbols-outlined">print</span>
        Export PDF
      </button>
    </div>

    <!-- Report Header Card -->
    <div class="glass-panel report-header-card">
      <div class="report-header-accent"></div>
      <div class="report-header-glow"></div>

      <div class="report-header-content">
        <div class="report-header-left">
          <div class="report-badge">
            <span class="material-symbols-outlined" style="font-size: 14px; animation: pulse-anim 2s infinite;">verified_user</span>
            SECURE RISK ASSESSMENT
          </div>

          <div>
            <h1 class="report-title text-glow-cyan">{{ report.title }}</h1>
            <p class="report-subtitle">Comprehensive threat analysis generated by Gemini AI Engine.</p>
          </div>

          <div class="report-meta">
            <div class="meta-chip">
              <span class="material-symbols-outlined" style="font-size: 14px; color: var(--color-surface-tint);">calendar_today</span>
              <span style="opacity: 0.6;">GENERATED:</span>
              <span>{{ new Date(report.createdAt).toLocaleDateString() }}</span>
            </div>
            <div class="meta-chip">
              <span class="material-symbols-outlined" style="font-size: 14px; color: var(--color-surface-tint);">database</span>
              <span style="opacity: 0.6;">SOURCE:</span>
              <span style="text-transform: uppercase;">{{ report.sourceType || 'text' }}</span>
            </div>
            <div class="meta-chip">
              <span class="material-symbols-outlined" style="font-size: 14px; color: var(--color-surface-tint);">fingerprint</span>
              <span style="opacity: 0.6;">ID:</span>
              <span>#{{ report._id?.substring(0, 8) }}</span>
            </div>
          </div>
        </div>

        <!-- Score Circle -->
        <div class="score-circle-container">
          <div class="score-circle-label">Risk Index</div>
          <div class="score-circle-wrapper">
            <svg width="128" height="128" style="transform: rotate(-90deg);">
              <circle cx="64" cy="64" r="54" stroke="rgba(255,255,255,0.1)" stroke-width="8" fill="transparent"/>
              <circle
                cx="64" cy="64" r="54"
                :stroke="getRiskColor(report.overallScore)"
                stroke-width="8"
                :stroke-dasharray="2 * Math.PI * 54"
                :stroke-dashoffset="2 * Math.PI * 54 * (1 - report.overallScore / 100)"
                stroke-linecap="round"
                fill="transparent"
                style="transition: stroke-dashoffset 1s ease-out;"
              />
            </svg>
            <div class="score-circle-value">
              <span class="score-number">{{ report.overallScore }}</span>
              <span class="score-denom">/100</span>
            </div>
          </div>
          <div class="score-level" :style="{ color: getRiskColor(report.overallScore) }">
            {{ getRiskLevelLabel(report.overallScore) }} CRITICALITY
          </div>
        </div>
      </div>
    </div>

    <!-- Bento Grid: Radar Chart + Threat Profile -->
    <div class="report-bento-grid">
      <!-- Risk Vector Chart -->
      <div class="glass-panel bento-card radar-card">
        <div class="bento-card-header">
          <h3 class="bento-card-title">
            <span class="bento-icon" style="background: rgba(0,219,233,0.1); color: var(--color-surface-tint);">
              <span class="material-symbols-outlined">radar</span>
            </span>
            Risk Vector Analysis
          </h3>
          <div class="live-badge">
            <span class="live-dot"></span> LIVE PROFILE
          </div>
        </div>
        <div class="chart-area">
          <ClientOnly>
            <Radar v-if="chartData" :data="chartData" :options="chartOptions" style="max-height: 350px;" />
            <template #fallback>
              <div style="display: flex; align-items: center; justify-content: center; height: 350px; color: var(--color-outline);">Loading chart...</div>
            </template>
          </ClientOnly>
        </div>
      </div>

      <!-- Threat Profile -->
      <div class="glass-panel bento-card profile-card">
        <div style="position: absolute; top: 0; right: 0; padding: 2rem; opacity: 0.08; pointer-events: none;">
          <span class="material-symbols-outlined" style="font-size: 120px;">security</span>
        </div>
        <h3 class="bento-card-title" style="margin-bottom: 2rem;">
          <span class="bento-icon" style="background: rgba(209,188,255,0.1); color: #d1bcff;">
            <span class="material-symbols-outlined">person_search</span>
          </span>
          Threat Profile
        </h3>

        <div class="profile-content">
          <!-- Confidence bar -->
          <div class="confidence-section">
            <div style="display: flex; justify-content: space-between; margin-bottom: 0.5rem;">
              <span style="font-size: 10px; letter-spacing: 0.2em; color: var(--color-outline); text-transform: uppercase;">AI Certainty Index</span>
              <span style="font-family: 'JetBrains Mono', monospace; font-size: 0.875rem; color: var(--color-surface-tint);">{{ report.confidenceScore }}%</span>
            </div>
            <div class="confidence-track">
              <div class="confidence-fill" :style="{ width: report.confidenceScore + '%' }"></div>
            </div>
          </div>

          <!-- Profile details grid -->
          <div class="profile-details-grid">
            <div class="profile-detail-card">
              <span class="detail-label">Intent Level</span>
              <p class="detail-value">{{ report.overallScore > 70 ? 'Hostile / Targeted' : 'Opportunistic' }}</p>
            </div>
            <div class="profile-detail-card">
              <span class="detail-label">Capability</span>
              <p class="detail-value">{{ report.overallScore > 60 ? 'Advanced / Persistent' : 'Moderate' }}</p>
            </div>
          </div>

          <!-- Attack vectors -->
          <div class="attack-vectors">
            <span class="vectors-label">Primary Attack Vectors</span>
            <div class="vectors-list">
              <div v-for="(score, cat) in report.categoryScores" :key="cat" v-show="score > 50" class="vector-item">
                <span class="vector-name">{{ cat }}</span>
                <span class="vector-score">{{ score }} PTS</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Findings & Recommendations -->
    <div class="report-findings-grid">
      <!-- Findings -->
      <div class="glass-panel bento-card">
        <h3 class="bento-card-title" style="margin-bottom: 2rem;">
          <span class="bento-icon" style="background: rgba(0,219,233,0.1); color: var(--color-surface-tint);">
            <span class="material-symbols-outlined">find_in_page</span>
          </span>
          Critical Findings
        </h3>
        <div class="findings-list">
          <div v-for="(finding, index) in report.findings" :key="index" class="finding-item">
            <div class="finding-icon">
              <span class="material-symbols-outlined">priority_high</span>
            </div>
            <div>
              <span style="font-size: 9px; letter-spacing: 0.2em; color: var(--color-outline); text-transform: uppercase; display: block; margin-bottom: 0.25rem;">Finding #{{ index + 1 }}</span>
              <p style="color: var(--color-on-background); line-height: 1.6; font-size: 0.9rem;">{{ finding }}</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Recommendations -->
      <div class="glass-panel bento-card">
        <h3 class="bento-card-title" style="margin-bottom: 2rem;">
          <span class="bento-icon" style="background: rgba(209,188,255,0.1); color: #d1bcff;">
            <span class="material-symbols-outlined">gavel</span>
          </span>
          Remediation Roadmap
        </h3>
        <div class="findings-list">
          <div v-for="(rec, index) in report.recommendations" :key="index" class="finding-item rec-item">
            <div class="finding-icon rec-icon">
              <span class="material-symbols-outlined">task_alt</span>
            </div>
            <div>
              <span style="font-size: 9px; letter-spacing: 0.2em; color: var(--color-outline); text-transform: uppercase; display: block; margin-bottom: 0.25rem;">Action Item</span>
              <p style="color: var(--color-on-background); line-height: 1.6; font-size: 0.9rem;">{{ rec }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Download Footer -->
    <div class="report-footer">
      <button @click="printReport" class="download-btn">
        <span class="material-symbols-outlined">download</span>
        DOWNLOAD FULL PDF DOSSIER
      </button>
    </div>
  </div>

  <!-- Error State -->
  <div v-else-if="error" class="report-error-state">
    <span class="material-symbols-outlined" style="font-size: 4rem; opacity: 0.4; color: #ef4444;">error</span>
    <h2 style="font-size: 1.5rem; font-weight: 600; color: var(--color-on-surface);">Report Not Found</h2>
    <p style="color: var(--color-outline);">The report you're looking for doesn't exist or has been removed.</p>
    <NuxtLink to="/dashboard" class="export-btn">Return to Dashboard</NuxtLink>
  </div>

  <!-- Loading State -->
  <div v-else class="report-loading-state">
    <div class="loading-spinner"></div>
    <p style="color: var(--color-outline); margin-top: 1rem;">Loading intelligence report...</p>
  </div>
</template>

<script setup>
import { ref, onMounted, computed } from 'vue';
import { useRoute, useRuntimeConfig } from '#imports';
import {
  Chart as ChartJS,
  RadialLinearScale,
  PointElement,
  LineElement,
  Filler,
  Tooltip,
  Legend
} from 'chart.js';
import { Radar } from 'vue-chartjs';

ChartJS.register(RadialLinearScale, PointElement, LineElement, Filler, Tooltip, Legend);

const route = useRoute();
const report = ref(null);
const error = ref(null);

const fetchReport = async () => {
  const config = useRuntimeConfig();
  try {
    const response = await fetch(`${config.public.apiBase}/reports/${route.params.id}`, {
      credentials: 'include'
    });
    if (!response.ok) throw new Error(response.status === 404 ? 'Report not found' : 'Failed to fetch report');
    const data = await response.json();
    report.value = data.report || data;
    error.value = null;
  } catch (err) {
    console.error('Error fetching report:', err);
    error.value = err.message;
  }
};

onMounted(fetchReport);

const getRiskColor = (score) => {
  if (score >= 66) return '#d1bcff';
  if (score >= 33) return '#eab308';
  return 'var(--color-surface-tint)';
};

const getRiskLevelLabel = (score) => {
  if (score >= 66) return 'CRITICAL';
  if (score >= 33) return 'MODERATE';
  return 'MINIMAL';
};

const printReport = () => window.print();

const chartData = computed(() => {
  if (!report.value?.categoryScores) return null;
  const cats = report.value.categoryScores;
  return {
    labels: ['Financial', 'Operational', 'Market', 'Legal', 'Reputational'],
    datasets: [{
      label: 'Risk Score',
      backgroundColor: 'rgba(0, 219, 233, 0.2)',
      borderColor: 'rgba(0, 219, 233, 1)',
      pointBackgroundColor: 'rgba(0, 219, 233, 1)',
      pointBorderColor: '#fff',
      data: [cats.financial || 0, cats.operational || 0, cats.market || 0, cats.legal || 0, cats.reputational || 0]
    }]
  };
});

const chartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  scales: {
    r: {
      angleLines: { color: 'rgba(255, 255, 255, 0.1)' },
      grid: { color: 'rgba(255, 255, 255, 0.05)' },
      pointLabels: { color: '#849495', font: { size: 11, family: 'Space Grotesk', weight: '600' } },
      ticks: { display: false, min: 0, max: 100 }
    }
  },
  plugins: { legend: { display: false } }
};
</script>

<style scoped>
.report-page { max-width: 1400px; }

.report-actions {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 2rem;
  gap: 1rem;
  flex-wrap: wrap;
}

.back-btn {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1.25rem;
  border-radius: 0.75rem;
  background: rgba(255,255,255,0.05);
  border: 1px solid rgba(255,255,255,0.1);
  color: var(--color-surface-tint);
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 0.1em;
  text-decoration: none;
  text-transform: uppercase;
  transition: all 0.2s;
}
.back-btn:hover { background: var(--color-surface-tint); color: #0c1324; }

.export-btn {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1.25rem;
  border-radius: 0.75rem;
  background: var(--color-surface-tint);
  border: none;
  color: #0c1324;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  cursor: pointer;
  transition: all 0.2s;
  text-decoration: none;
}
.export-btn:hover { filter: brightness(1.1); box-shadow: 0 0 30px rgba(0,219,233,0.4); }

.report-header-card {
  border-radius: 1rem;
  padding: 2.5rem;
  margin-bottom: 2rem;
  position: relative;
  overflow: hidden;
}
.report-header-accent {
  position: absolute;
  top: 0; left: 0;
  width: 100%; height: 4px;
  background: linear-gradient(to right, var(--color-surface-tint), #a855f7, var(--color-surface-tint));
  opacity: 0.7;
}
.report-header-glow {
  position: absolute;
  top: -6rem; right: -6rem;
  width: 16rem; height: 16rem;
  background: rgba(0,219,233,0.1);
  border-radius: 50%;
  filter: blur(100px);
  pointer-events: none;
}
.report-header-content {
  display: flex;
  flex-direction: column;
  gap: 2rem;
  position: relative;
  z-index: 1;
}
@media (min-width: 1024px) {
  .report-header-content { flex-direction: row; align-items: flex-start; justify-content: space-between; }
}
.report-header-left { display: flex; flex-direction: column; gap: 1.5rem; flex: 1; }

.report-badge {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.375rem 1rem;
  border-radius: 9999px;
  background: rgba(0,219,233,0.1);
  border: 1px solid rgba(0,219,233,0.2);
  color: var(--color-surface-tint);
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 0.2em;
  text-transform: uppercase;
  width: fit-content;
}

.report-title {
  font-size: clamp(2rem, 4vw, 3.5rem);
  font-weight: 700;
  color: var(--color-on-surface);
  line-height: 1.1;
  margin: 0;
}
.report-subtitle {
  font-size: 1.125rem;
  color: var(--color-outline);
  opacity: 0.8;
  max-width: 40rem;
  margin-top: 0.5rem;
}

.report-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem;
  padding-top: 1rem;
  border-top: 1px solid rgba(255,255,255,0.05);
}
.meta-chip {
  display: flex;
  align-items: center;
  gap: 0.4rem;
  padding: 0.25rem 0.75rem;
  border-radius: 0.375rem;
  background: rgba(255,255,255,0.05);
  font-family: 'JetBrains Mono', monospace;
  font-size: 11px;
  color: var(--color-on-surface);
}

.score-circle-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 2rem;
  border-radius: 1rem;
  background: rgba(255,255,255,0.03);
  border: 1px solid rgba(255,255,255,0.05);
  min-width: 220px;
}
.score-circle-label {
  font-size: 10px;
  letter-spacing: 0.3em;
  color: var(--color-outline);
  text-transform: uppercase;
  margin-bottom: 1rem;
}
.score-circle-wrapper { position: relative; width: 128px; height: 128px; display: flex; align-items: center; justify-content: center; }
.score-circle-value { position: absolute; display: flex; flex-direction: column; align-items: center; }
.score-number { font-size: 2.5rem; font-weight: 700; color: var(--color-on-surface); line-height: 1; }
.score-denom { font-size: 10px; color: var(--color-outline); letter-spacing: 0.1em; }
.score-level { margin-top: 1rem; font-size: 11px; font-weight: 700; letter-spacing: 0.2em; text-transform: uppercase; }

/* Bento grid */
.report-bento-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 1.5rem;
  margin-bottom: 1.5rem;
}
@media (min-width: 1024px) {
  .report-bento-grid { grid-template-columns: 7fr 5fr; }
}

.bento-card { border-radius: 1rem; padding: 2rem; position: relative; overflow: hidden; }
.radar-card { display: flex; flex-direction: column; }
.profile-card {}

.bento-card-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 2rem; }
.bento-card-title {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  font-size: 1.25rem;
  font-weight: 600;
  color: var(--color-on-surface);
  margin: 0;
}
.bento-icon {
  padding: 0.5rem;
  border-radius: 0.5rem;
  display: flex;
  align-items: center;
  justify-content: center;
}
.live-badge {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 0.15em;
  color: var(--color-outline);
  text-transform: uppercase;
  background: rgba(255,255,255,0.05);
  padding: 0.25rem 0.75rem;
  border-radius: 9999px;
  border: 1px solid rgba(255,255,255,0.08);
}
.live-dot {
  width: 8px; height: 8px; border-radius: 50%;
  background: var(--color-surface-tint);
  animation: pulse-anim 2s infinite;
}
.chart-area { flex: 1; min-height: 300px; display: flex; align-items: center; justify-content: center; }

/* Threat profile */
.profile-content { display: flex; flex-direction: column; gap: 1.5rem; }
.confidence-track {
  height: 10px;
  background: rgba(255,255,255,0.05);
  border-radius: 9999px;
  overflow: hidden;
  border: 1px solid rgba(255,255,255,0.05);
  padding: 2px;
}
.confidence-fill {
  height: 100%;
  background: linear-gradient(to right, var(--color-surface-tint), #a855f7);
  border-radius: 9999px;
  box-shadow: 0 0 15px rgba(0,219,233,0.4);
  transition: width 1s ease-out;
}

.profile-details-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
.profile-detail-card {
  padding: 1rem;
  border-radius: 0.75rem;
  background: rgba(255,255,255,0.03);
  border: 1px solid rgba(255,255,255,0.06);
}
.detail-label { font-size: 9px; letter-spacing: 0.2em; text-transform: uppercase; color: var(--color-outline); display: block; margin-bottom: 0.4rem; }
.detail-value { color: var(--color-on-surface); font-weight: 500; font-size: 0.9rem; margin: 0; }

.vectors-label { font-size: 10px; letter-spacing: 0.2em; text-transform: uppercase; color: var(--color-outline); display: block; padding-bottom: 0.5rem; border-bottom: 1px solid rgba(255,255,255,0.05); margin-bottom: 0.75rem; }
.vectors-list { display: flex; flex-direction: column; gap: 0.5rem; }
.vector-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.625rem 0.75rem;
  border-radius: 0.5rem;
  background: rgba(0,219,233,0.05);
  border-left: 2px solid var(--color-surface-tint);
}
.vector-name { font-size: 0.8rem; font-weight: 500; color: var(--color-on-surface); text-transform: capitalize; }
.vector-score { font-family: 'JetBrains Mono', monospace; font-size: 10px; color: var(--color-surface-tint); }

/* Findings grid */
.report-findings-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 1.5rem;
  margin-bottom: 1.5rem;
}
@media (min-width: 1024px) {
  .report-findings-grid { grid-template-columns: 1fr 1fr; }
}

.findings-list { display: flex; flex-direction: column; gap: 1rem; }
.finding-item {
  display: flex;
  gap: 1rem;
  padding: 1.25rem;
  border-radius: 1rem;
  background: rgba(255,255,255,0.02);
  border: 1px solid rgba(255,255,255,0.06);
  transition: all 0.2s;
}
.finding-item:hover { border-color: rgba(0,219,233,0.2); background: rgba(0,219,233,0.04); }
.finding-icon {
  width: 2.5rem; height: 2.5rem; border-radius: 50%;
  background: rgba(0,219,233,0.1);
  display: flex; align-items: center; justify-content: center;
  flex-shrink: 0;
  color: var(--color-surface-tint);
  transition: transform 0.2s;
}
.finding-item:hover .finding-icon { transform: scale(1.1); }
.rec-item:hover { border-color: rgba(209,188,255,0.2); background: rgba(209,188,255,0.04); }
.rec-icon { background: rgba(209,188,255,0.1); color: #d1bcff; }

/* Footer */
.report-footer {
  display: flex;
  justify-content: center;
  padding-top: 2rem;
  border-top: 1px solid rgba(255,255,255,0.05);
  margin-top: 1rem;
}
.download-btn {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 1rem 2.5rem;
  border-radius: 0.75rem;
  background: var(--color-surface-tint);
  color: #0c1324;
  font-weight: 700;
  letter-spacing: 0.2em;
  font-size: 0.8rem;
  text-transform: uppercase;
  border: none;
  cursor: pointer;
  transition: all 0.3s;
  box-shadow: 0 8px 25px rgba(0,219,233,0.25);
}
.download-btn:hover { filter: brightness(1.1); box-shadow: 0 12px 40px rgba(0,219,233,0.45); }

/* States */
.report-error-state, .report-loading-state {
  min-height: 60vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  gap: 1rem;
}

.loading-spinner {
  width: 3rem; height: 3rem;
  border: 2px solid rgba(0,219,233,0.2);
  border-top-color: var(--color-surface-tint);
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}

@keyframes spin { to { transform: rotate(360deg); } }
@keyframes pulse-anim { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }
</style>