<template>
  <div class="fade-in-up" v-if="report">
    <div class="flex flex-col md:flex-row md:items-center justify-between mb-margin gap-4">
      <NuxtLink to="/" class="flex items-center justify-center gap-2 px-4 py-3 rounded-lg bg-white/5 border border-white/10 text-surface-tint font-label-caps text-[10px] md:text-label-caps hover:bg-surface-tint hover:text-background transition-all shadow-[0_0_15px_rgba(0,219,233,0.1)] hover:shadow-[0_0_30px_rgba(0,219,233,0.3)] min-h-[44px]">
        <span class="material-symbols-outlined text-sm">arrow_back</span> Back to Dashboard
      </NuxtLink>
      <button @click="printReport" class="flex items-center justify-center gap-2 px-4 py-3 rounded-lg bg-surface-tint text-background font-label-caps text-[10px] md:text-label-caps shadow-[0_0_20px_rgba(0,219,233,0.3)] hover:shadow-[0_0_40px_rgba(0,219,233,0.5)] transition-all min-h-[44px]">
        <span class="material-symbols-outlined text-sm">print</span> Export PDF
      </button>
    </div>

    <!-- Premium Report Header -->
    <div class="glass-panel rounded-2xl mb-margin p-8 md:p-10 overflow-hidden relative border border-outline-variant/20 dark:border-white/10 shadow-[0_20px_50px_rgba(0,0,0,0.1)] dark:shadow-[0_20px_50px_rgba(0,0,0,0.5)]">
      <div class="absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r from-surface-tint via-primary to-surface-tint opacity-70"></div>
      <div class="absolute -top-24 -right-24 w-64 h-64 bg-surface-tint/10 rounded-full blur-[100px] pointer-events-none"></div>
      
      <div class="flex flex-col lg:flex-row lg:items-start justify-between gap-8 relative z-10">
        <div class="space-y-6 flex-1">
          <div class="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-surface-tint/10 border border-surface-tint/20 text-surface-tint font-label-caps text-[10px] tracking-[0.2em] shadow-[0_0_15px_rgba(0,219,233,0.1)]">
            <span class="material-symbols-outlined text-sm animate-pulse">verified_user</span> 
            SECURE RISK ASSESSMENT
          </div>
          
          <div class="space-y-2">
            <h1 class="font-headline-xl text-4xl md:text-5xl lg:text-6xl text-on-surface text-glow-cyan tracking-tight leading-tight">
              {{ report.title }}
            </h1>
            <p class="text-on-surface-variant font-body-lg text-lg opacity-80 max-w-2xl">
              Comprehensive threat analysis and vulnerability assessment generated by Gemini AI Engine.
            </p>
          </div>

          <div class="flex flex-wrap items-center gap-6 font-data-mono text-xs text-outline pt-4 border-t border-outline-variant/10 dark:border-white/5">
            <div class="flex items-center gap-2 px-3 py-1 rounded-md bg-surface-variant/30 dark:bg-white/5">
              <span class="material-symbols-outlined text-sm text-surface-tint">calendar_today</span>
              <span class="opacity-70">GENERATED:</span>
              <span class="text-on-surface">{{ new Date(report.createdAt).toLocaleDateString() }}</span>
            </div>
            <div class="flex items-center gap-2 px-3 py-1 rounded-md bg-surface-variant/30 dark:bg-white/5">
              <span class="material-symbols-outlined text-sm text-surface-tint">database</span>
              <span class="opacity-70">SOURCE:</span>
              <span class="text-on-surface uppercase">{{ report.sourceType }}</span>
            </div>
            <div class="flex items-center gap-2 px-3 py-1 rounded-md bg-surface-variant/30 dark:bg-white/5">
              <span class="material-symbols-outlined text-sm text-surface-tint">fingerprint</span>
              <span class="opacity-70">ID:</span>
              <span class="text-on-surface">#{{ report._id.substring(0, 8) }}</span>
            </div>
          </div>
        </div>

            <!-- Animated Ring -->
            <svg class="absolute inset-0 w-full h-full -rotate-90 pointer-events-none" viewBox="0 0 100 100">
               <circle cx="50" cy="50" r="46" fill="none" stroke="currentColor" stroke-width="2" stroke-dasharray="289" :stroke-dashoffset="289 - (289 * report.overallScore / 100)" class="transition-all duration-1000 ease-out opacity-50" :class="getRiskColorClass(report.overallScore, 'text')"></circle>
            </svg>
          </div>
          <div class="px-6 py-2 rounded-lg bg-white/5 border border-white/10 text-outline font-label-caps text-[10px] tracking-widest uppercase">
            {{ getRiskLevelLabel(report.overallScore) }} Criticality
          </div>
        </div>
      </div>
    </div>

    <!-- Threat Analysis Bento Grid -->
    <div class="grid grid-cols-1 lg:grid-cols-12 gap-gutter mb-margin">
      <!-- Risk Vector Visualization -->
      <div class="lg:col-span-7">
        <div class="glass-panel rounded-2xl p-8 h-full flex flex-col border border-white/10">
          <div class="flex items-center justify-between mb-8">
            <h3 class="font-headline-md text-2xl text-on-surface flex items-center gap-3">
              <span class="p-2 rounded-lg bg-surface-tint/10 text-surface-tint">
                <span class="material-symbols-outlined block">radar</span>
              </span>
              Risk Vector Analysis
            </h3>
            <div class="flex items-center gap-2 text-[10px] font-label-caps text-outline bg-white/5 px-3 py-1 rounded-full">
              <span class="w-2 h-2 rounded-full bg-surface-tint animate-pulse"></span> LIVE PROFILE
            </div>
          </div>
          <div class="flex-1 min-h-[350px] relative flex items-center justify-center">
            <Radar v-if="chartData" :data="chartData" :options="chartOptions" />
          </div>
        </div>
      </div>

      <!-- Threat Actor Profile Section -->
      <div class="lg:col-span-5">
        <div class="glass-panel rounded-2xl p-8 h-full border border-white/10 relative overflow-hidden">
          <div class="absolute top-0 right-0 p-8 opacity-10 pointer-events-none">
            <span class="material-symbols-outlined text-[120px]">security</span>
          </div>
          
          <h3 class="font-headline-md text-2xl text-on-surface flex items-center gap-3 mb-8">
            <span class="p-2 rounded-lg bg-secondary-container/10 text-secondary-container">
              <span class="material-symbols-outlined block">person_search</span>
            </span>
            Threat Profile
          </h3>

          <div class="space-y-8 relative z-10">
            <!-- Confidence Meter -->
            <div class="space-y-4">
              <div class="flex items-center justify-between">
                <span class="font-label-caps text-[10px] tracking-widest text-outline uppercase">AI Certainty Index</span>
                <span class="font-data-mono text-sm text-surface-tint">{{ report.confidenceScore }}%</span>
              </div>
              <div class="h-3 w-full bg-white/5 rounded-full overflow-hidden p-0.5 border border-white/5">
                <div class="h-full bg-gradient-to-r from-surface-tint to-primary rounded-full shadow-[0_0_15px_rgba(0,219,233,0.5)] transition-all duration-1000" :style="{ width: report.confidenceScore + '%' }"></div>
              </div>
            </div>

            <!-- Profile Details -->
            <div class="grid grid-cols-2 gap-4">
              <div class="p-4 rounded-xl bg-white/5 border border-white/5 space-y-2">
                <span class="text-[9px] font-label-caps text-outline tracking-wider uppercase">Intent Level</span>
                <p class="text-on-surface font-medium">{{ report.overallScore > 70 ? 'Hostile / Targeted' : 'Opportunistic' }}</p>
              </div>
              <div class="p-4 rounded-xl bg-white/5 border border-white/5 space-y-2">
                <span class="text-[9px] font-label-caps text-outline tracking-wider uppercase">Capability</span>
                <p class="text-on-surface font-medium">{{ report.overallScore > 60 ? 'Advanced / Persistent' : 'Moderate' }}</p>
              </div>
            </div>

            <!-- Threat Vectors List -->
            <div class="space-y-4">
              <span class="text-[10px] font-label-caps text-outline tracking-widest uppercase block border-b border-white/5 pb-2">Primary Attack Vectors</span>
              <div class="space-y-3">
                <div v-for="(cat, score) in report.categoryScores" :key="cat" v-show="score > 50" class="flex items-center justify-between p-3 rounded-lg bg-surface-tint/5 border-l-2 border-surface-tint">
                  <span class="text-xs font-medium text-on-surface capitalize">{{ cat }}</span>
                  <span class="text-[10px] font-data-mono text-surface-tint">{{ score }} PTS</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Findings & Recommendations -->
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-gutter mb-margin">
      <!-- Strategic Findings -->
      <div class="glass-panel rounded-2xl p-8 border border-white/10">
        <h3 class="font-headline-md text-2xl text-on-surface flex items-center gap-3 mb-8">
          <span class="p-2 rounded-lg bg-surface-tint/10 text-surface-tint">
            <span class="material-symbols-outlined block">find_in_page</span>
          </span>
          Critical Findings
         </h3>
        <div class="space-y-4">
          <div v-for="(finding, index) in report.findings" :key="index" class="group flex gap-5 p-6 rounded-2xl bg-white/[0.03] border border-white/5 hover:border-surface-tint/30 hover:bg-white/[0.05] transition-all">
            <div class="w-10 h-10 rounded-full bg-surface-tint/10 flex items-center justify-center shrink-0 group-hover:scale-110 transition-transform">
              <span class="material-symbols-outlined text-surface-tint text-xl">priority_high</span>
            </div>
            <div class="space-y-1">
              <span class="text-[9px] font-label-caps text-outline tracking-widest uppercase">Finding #{{ index + 1 }}</span>
              <p class="text-on-surface-variant leading-relaxed">{{ finding }}</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Mitigation Roadmap -->
      <div class="glass-panel rounded-2xl p-8 border border-white/10">
        <h3 class="font-headline-md text-2xl text-on-surface flex items-center gap-3 mb-8">
          <span class="p-2 rounded-lg bg-secondary-container/10 text-secondary-container">
            <span class="material-symbols-outlined block">gavel</span>
          </span>
          Remediation Roadmap
        </h3>
        <div class="space-y-4">
          <div v-for="(rec, index) in report.recommendations" :key="index" class="group flex gap-5 p-6 rounded-2xl bg-secondary-container/5 border border-white/5 hover:border-secondary-container/30 hover:bg-secondary-container/10 transition-all">
            <div class="w-10 h-10 rounded-full bg-secondary-container/10 flex items-center justify-center shrink-0 group-hover:scale-110 transition-transform">
              <span class="material-symbols-outlined text-secondary-container text-xl">task_alt</span>
            </div>
            <div class="space-y-1">
              <span class="text-[9px] font-label-caps text-outline tracking-widest uppercase">Action Item</span>
              <p class="text-on-surface-variant leading-relaxed">{{ rec }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Export Controls -->
    <div class="flex items-center justify-center pt-8 border-t border-white/5">
       <button @click="printReport" class="flex items-center gap-3 px-8 py-4 rounded-xl bg-surface-tint text-background font-label-caps tracking-widest hover:brightness-110 transition-all shadow-2xl hover:shadow-surface-tint/40">
         <span class="material-symbols-outlined">download</span> DOWNLOAD FULL PDF DOSSIER
       </button>
    </div>
  </div>

  <div v-else-if="error" class="min-h-[60vh] flex flex-col items-center justify-center text-center space-y-stack-lg">
    <span class="material-symbols-outlined text-display-lg text-error opacity-50">error</span>
    <h2 class="font-headline-xl text-on-surface">Report Not Found</h2>
    <p class="text-outline">The report you're looking for doesn't exist or has been removed.</p>
    <NuxtLink to="/" class="px-stack-lg py-stack-md bg-surface-tint text-background rounded-lg font-label-caps text-label-caps shadow-[0_0_20px_rgba(0,219,233,0.3)]">Return Home</NuxtLink>
  </div>
  
  <div v-else class="min-h-[60vh] flex items-center justify-center">
    <div class="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-surface-tint"></div>
  </div>
</template>

<script setup>
import { ref, onMounted, computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import {
  Chart as ChartJS,
  RadialLinearScale,
  PointElement,
  LineElement,
  Filler,
  Tooltip,
  Legend
} from 'chart.js';
import { Radar } from 'vue-chartjs';

ChartJS.register(
  RadialLinearScale,
  PointElement,
  LineElement,
  Filler,
  Tooltip,
  Legend
);

const route = useRoute();
const router = useRouter();
const report = ref(null);
const error = ref(null);

const fetchReport = async () => {
    try {
        // ✅ FIXED: Use deployed backend URL instead of localhost
        const response = await fetch(`https://riskanalyzer-backend.onrender.com/api/reports/${route.params.id}`);
        
        if (!response.ok) {
            if (response.status === 404) {
                throw new Error('Report not found');
            }
            throw new Error('Failed to fetch report');
        }
        
        const data = await response.json();
        // Handle both response formats
        report.value = data.report || data;
        error.value = null;
        
    } catch (err) {
        console.error('Error fetching report:', err);
        error.value = err.message;
    }
};

onMounted(fetchReport);

const getRiskColorClass = (score, type = 'text') => {
    if (score >= 66) {
        return type === 'text' ? 'text-secondary-container' : (type === 'border' ? 'border-secondary-container/50' : 'bg-secondary-container');
    }
    if (score >= 33) {
        return type === 'text' ? 'text-yellow-500' : (type === 'border' ? 'border-yellow-500/50' : 'bg-yellow-500');
    }
    return type === 'text' ? 'text-surface-tint' : (type === 'border' ? 'border-surface-tint/50' : 'bg-surface-tint');
};

const getRiskLevelLabel = (score) => {
    if (score >= 66) return 'CRITICAL';
    if (score >= 33) return 'MODERATE';
    return 'MINIMAL';
};

const printReport = () => window.print();

const chartData = computed(() => {
    if (!report.value || !report.value.categoryScores) return null;
    const cats = report.value.categoryScores;
    return {
        labels: ['Financial', 'Operational', 'Market', 'Legal', 'Reputational'],
        datasets: [{
            label: 'Risk Score',
            backgroundColor: 'rgba(0, 219, 233, 0.2)',
            borderColor: 'rgba(0, 219, 233, 1)',
            pointBackgroundColor: 'rgba(0, 219, 233, 1)',
            pointBorderColor: '#fff',
            pointHoverBackgroundColor: '#fff',
            pointHoverBorderColor: 'rgba(0, 219, 233, 1)',
            data: [
                cats.financial || 0, 
                cats.operational || 0, 
                cats.market || 0, 
                cats.legal || 0, 
                cats.reputational || 0
            ]
        }]
    };
});

const chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    scales: {
        r: {
            angleLines: { color: 'rgba(255, 255, 255, 0.1)' },
            grid: { color: 'rgba(255, 255, 255, 0.05)' },
            pointLabels: { 
              color: '#849495', 
              font: { 
                size: 11, 
                family: 'Space Grotesk',
                weight: '600'
              } 
            },
            ticks: { display: false, min: 0, max: 100 }
        }
    },
    plugins: {
        legend: { display: false }
    }
};
</script>

<style scoped>
/* Scoped styles if needed */
</style>